config rule
	option name 'A_WEBPROXY_UIEMBEDDINGS_HTTP'
	option family 'ipv4'
	list proto 'tcp'
	option src 'VMRISK'
	list src_ip '192.168.2.67'
	option dest 'VMRISK'
	list dest_ip '192.168.2.75'
	option dest_port '8000'
	option target 'ACCEPT'

config host
	option name 'UIEmbeddings'
	option dns '1'
	option mac '8E:74:D1:A2:D8:0C'
	option ip '192.168.2.75'
	option leasetime '12h'
